# Generated by Django 5.2.5 on 2025-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
